### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by Tsunaou** [Tsunaou/mongodb#3]
# MongoDB Transaction Snapshot Isolation Checking
## Replica Set和Sharded Cluster 两种部署下操作历史的获取
- [x] MongoDB测试版本的更新
- [x] Replica Set rw-registers 代码的迁移
  - [x] 主要是2种部署的逻辑，最好是写成可配置的
- [x] Sharded Cluster rw-register Trace的获取

## Oplog的解析
- [x] 得到commitTimestamp
- [x] 解析applyOps里的条目，并与jepsen的history.edn整合对应

## Checking算法的设计
- [ ] read timestamp和start timestamp都无法直接获取，应该怎么办
